/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PageTwoImport } from './routes/page-two'
import { Route as PageOneImport } from './routes/page-one'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PageTwoRoute = PageTwoImport.update({
  path: '/page-two',
  getParentRoute: () => rootRoute,
} as any)

const PageOneRoute = PageOneImport.update({
  path: '/page-one',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/page-one': {
      preLoaderRoute: typeof PageOneImport
      parentRoute: typeof rootRoute
    }
    '/page-two': {
      preLoaderRoute: typeof PageTwoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PageOneRoute,
  PageTwoRoute,
])

/* prettier-ignore-end */
